--- 
name: unixODBC 2.3.0 Source
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-unixodbc-2.3.0-all-src-2
platform_vendor: all
description: unixODBC 2.3.0 Source
platform_arch: all
distribution_file_uuid: 8f07cae298c22b2fbb2779c0f0edf4b69acbd2ccfd61ff320e1f7d7ed299c15e
distribution_version: 2
distribution_flavor: ""
distribution_raw_file: 2.3.0/src/unixODBC-2.3.0.tar.gz
notify: "yes"
package_version: 2.3.0
package_id: unixodbc
release_date: "2011-05-10"
distribution_notes: ""
distribution_type: src
